update commands to new version
inductiva/sph-demos pull request #4
Opened 2024-01-24 16:35 UTC by AugustoPeres

2024-01-24 16:43 UTC, IvanPombo requested changes
You also need to change in the `lib/scenarios.py`. Then provide proof of working, and we can give a greenlight!

2024-01-24 17:03 UTC, IvanPombo requested changes
Address also the docs.

2024-01-24 17:22 UTC, AugustoPeres commented
<img width="1436" alt="Screenshot 2024-01-24 at 17 03 21" src="https://github.com/inductiva/sph-demos/assets/33664950/b0e0ce61-0c38-4af5-b5a4-fcd86ed2c1af">
have not tested 2 because first need to install ffmpeg.
<img width="1434" alt="Screenshot 2024-01-24 at 17 19 38" src="https://github.com/inductiva/sph-demos/assets/33664950/9f5eec34-969d-4a5c-a856-317140c7efcf">

2024-01-24 17:25 UTC, IvanPombo commented
> <img alt="Screenshot 2024-01-24 at 17 03 21" width="1436" src="https://private-user-images.githubusercontent.com/33664950/299396570-b0e0ce61-0c38-4af5-b5a4-fcd86ed2c1af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTc0MzAsIm5iZiI6MTcwNjExNzEzMCwicGF0aCI6Ii8zMzY2NDk1MC8yOTkzOTY1NzAtYjBlMGNlNjEtMGMzOC00YWY1LWI1YTQtZmNkODZlZDJjMWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE3MjUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZWZkYjNjY2NkNTQzZTE3N2Y3MzRlNGQxNzlhNWMxMWE1MmM3MWE1OWRjYmRjMTg5Y2IzZTUwODhiMTM4NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BOdhVkNd0bAlwvjRu5txiKTwCN9aIorfcGoHeDCGWsw"> have not tested 2 because first need to install ffmpeg. <img alt="Screenshot 2024-01-24 at 17 19 38" width="1434" src="https://private-user-images.githubusercontent.com/33664950/299401503-9f5eec34-969d-4a5c-a856-317140c7efcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTc0MzAsIm5iZiI6MTcwNjExNzEzMCwicGF0aCI6Ii8zMzY2NDk1MC8yOTk0MDE1MDMtOWY1ZWVjMzQtOTY5ZC00YTVjLWE4NTYtMzE3MTQwYzdlZmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE3MjUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMzQ4ODZmMGU5ZWU5YWFlZjYxZmU1MjE2YzkyMjVhZmE4YTEwMDcxZWUxNDkwYWFhOTRjZTdmNWQ1MDRkOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NQRfKcRx_HGyHJE1wkE9a_D7s_A5WJx1VPcukmqXLnE">

The doc `docs/1_SPH_SIMULATIONS.md` also needs to be updated.

2024-01-24 17:38 UTC, IvanPombo approved these changes
LGTM!

2024-01-24 17:38 UTC, IvanPombo commented on docs/1_SPH_SIMULATIONS.md
> +    "partvtk -dirin flow_cylinder/data -savevtk vtk/PartFluid "-onlytype:+fluid"
Typo, extra "..

```suggestion
    "partvtk -dirin flow_cylinder/data -savevtk vtk/PartFluid -onlytype:+fluid"
```

2024-01-24 17:45 UTC, AugustoPeres commented
Could you also run the scripts from your side?

2024-01-25 10:05 UTC, IvanPombo commented
> Could you also run the scripts from your side?

@AugustoPeres this is also tested and ready to go!

2024-01-25 10:27 UTC, merged